## **Basic Tensors**

In [4]:
import tensorflow as tf
print(tf.__version__)

2.11.0


In [54]:
physical_devices = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physical_devices[0], True)

[]

In [11]:
x = tf.constant(4, shape=(1,1), dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [14]:
x = tf.constant([[1,2,3],
                 [4,5,6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [22]:
x = tf.constant([[[1,2,3],
                  [4,5,6],
                  [2,3,9]],
                 [[7,8,9],
                  [2,5,6],
                  [3,4,7]]])
print(x)
print(x[0][1][2])

tf.Tensor(
[[[1 2 3]
  [4 5 6]
  [2 3 9]]

 [[7 8 9]
  [2 5 6]
  [3 4 7]]], shape=(2, 3, 3), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


In [26]:
x = tf.ones((3,3))
x = tf.zeros((2,3))
x = tf.eye(3) # identity matrix
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [32]:
# normal distribution
x = tf.random.normal((4,4), mean = 0, stddev=1)
print(x)

tf.Tensor(
[[-0.9121928  -1.6864858  -2.4917152   2.6043758 ]
 [ 1.1664013  -0.7048528   0.9460205   0.2817023 ]
 [ 0.00381061  0.45072925 -1.344847    0.5297853 ]
 [-1.3141226   1.4588739   2.3007512  -0.86698973]], shape=(4, 4), dtype=float32)


In [34]:
# uniform distribution
# create 2 samples of 10x10 pixels images
x = tf.random.uniform((2, 10, 10), minval=0, maxval=225)
print(x)

tf.Tensor(
[[[2.09486633e+02 1.61768295e+02 2.12972794e+02 6.96707840e+01
   1.38437439e+02 2.60345936e+00 1.98889908e+02 1.51986755e+02
   9.10583115e+00 1.27944317e+01]
  [1.64445786e+02 2.21812897e+02 5.09181442e+01 1.67036606e+02
   6.39729118e+01 1.86417953e+02 2.57643337e+01 2.19767548e+02
   1.38607208e+02 1.10210197e+02]
  [1.78363358e+02 1.50008728e+02 1.40690445e+02 1.37651993e+02
   1.12264929e+01 3.53543053e+01 1.13362709e+02 2.19735809e+02
   1.54094650e+02 1.59201441e+01]
  [1.11426392e+02 1.36594315e+02 2.68848534e+01 2.62539711e+01
   1.14456940e+02 1.52131592e+02 1.50240448e+02 1.81371033e+02
   7.54761581e+01 8.87760773e+01]
  [2.14563690e+02 6.11053619e+01 4.10633049e+01 1.78880806e+01
   1.67359543e+02 1.67514687e+01 4.51158829e+01 7.79047318e+01
   1.87946838e+02 1.61883377e+02]
  [1.80523102e+02 1.35785217e+02 1.82274826e+02 9.10689392e+01
   1.02289879e+02 3.71831942e+00 6.97934113e+01 6.63790436e+01
   1.01535477e+02 5.72512131e+01]
  [1.23817101e+02 1.21772018e

In [39]:
# range
x = tf.range(9)
y = tf.range(start=1, limit=10, delta=2)
print(x)
# cast
y = tf.cast(y, dtype=tf.float64)
print(y)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


## **Mathematical Operations**

In [44]:
x = tf.constant([1,2,3])
y = tf.constant([4,5,6])

z = x + y
z = tf.add(x,y)

z = x - y
z = tf.subtract(x,y)

z = x / y
z = tf.divide(x,y)

z = x * y
z = tf.multiply(x,y)

print(z)

tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)


In [47]:
z = tf.tensordot(x, y, axes=1)
z = tf.reduce_sum(x*y, axis=0)
print(z)

tf.Tensor(32, shape=(), dtype=int32)


In [48]:
# element-wise operations
z = x ** 5
print(z)

tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


In [50]:
# matrix multiplication
m = tf.random.normal((4,5))
n = tf.random.normal((5,2))
print(m)
print(n)

mn = tf.matmul(m,n)
mn = m @ n
print(mn)

tf.Tensor(
[[ 0.8519905  -0.1779189   0.80547446  1.3214501  -2.2902424 ]
 [-0.31188396 -0.7357957   0.17913713 -0.08800738 -0.44645262]
 [-1.5119206   0.45748985  1.832193    0.5921169   0.44879144]
 [-0.46349284 -0.49323368 -2.3482943   0.41159263 -0.09693105]], shape=(4, 5), dtype=float32)
tf.Tensor(
[[ 1.4345157   0.2835907 ]
 [ 0.3733034  -0.21598874]
 [-0.21370585  0.23981018]
 [-0.08053378 -0.01082744]
 [ 0.6555969   0.39657283]], shape=(5, 2), dtype=float32)
tf.Tensor(
[[-0.6242557  -0.44934982]
 [-1.0459656  -0.06266298]
 [-2.1431007   0.08336664]
 [-0.4438642  -0.6309509 ]], shape=(4, 2), dtype=float32)


## **Slicing and Indexing**

In [57]:
m = tf.random.normal((4,5))
print(m)

tf.Tensor(
[[-0.05538731  0.78840816 -1.7234225   1.2485718  -0.6662699 ]
 [ 0.9634895   1.5275403  -1.2400384   0.8683419  -1.6852088 ]
 [ 0.15758198 -1.0328375  -0.65537715 -0.7304976  -0.30527896]
 [ 1.61065     0.7647484   1.4106855  -0.8583765  -1.0242368 ]], shape=(4, 5), dtype=float32)


In [64]:
print(m[:,1]) # access column
print()
print(m[::2,::2]) # skip value
print()
print(m[::-1]) # reverse the row
print()
print(m[:,::-1]) # reverse the column
print()
print(m[::-1,::-1]) # reverse the all dataset

tf.Tensor([ 0.78840816  1.5275403  -1.0328375   0.7647484 ], shape=(4,), dtype=float32)

tf.Tensor(
[[-0.05538731 -1.7234225  -0.6662699 ]
 [ 0.15758198 -0.65537715 -0.30527896]], shape=(2, 3), dtype=float32)

tf.Tensor(
[[ 1.61065     0.7647484   1.4106855  -0.8583765  -1.0242368 ]
 [ 0.15758198 -1.0328375  -0.65537715 -0.7304976  -0.30527896]
 [ 0.9634895   1.5275403  -1.2400384   0.8683419  -1.6852088 ]
 [-0.05538731  0.78840816 -1.7234225   1.2485718  -0.6662699 ]], shape=(4, 5), dtype=float32)

tf.Tensor(
[[-0.6662699   1.2485718  -1.7234225   0.78840816 -0.05538731]
 [-1.6852088   0.8683419  -1.2400384   1.5275403   0.9634895 ]
 [-0.30527896 -0.7304976  -0.65537715 -1.0328375   0.15758198]
 [-1.0242368  -0.8583765   1.4106855   0.7647484   1.61065   ]], shape=(4, 5), dtype=float32)

tf.Tensor(
[[-1.0242368  -0.8583765   1.4106855   0.7647484   1.61065   ]
 [-0.30527896 -0.7304976  -0.65537715 -1.0328375   0.15758198]
 [-1.6852088   0.8683419  -1.2400384   1.5275403   0.9634895 ]


## **Reshaping**

In [66]:
x = tf.random.normal((9,))
print(x)
x = tf.reshape(x, (3,3))
print(x)

tf.Tensor(
[-0.60639316 -1.5211961  -0.39179838  0.3352423   1.3196161   0.48279214
 -0.99884546  0.52961075  0.13366567], shape=(9,), dtype=float32)
tf.Tensor(
[[-0.60639316 -1.5211961  -0.39179838]
 [ 0.3352423   1.3196161   0.48279214]
 [-0.99884546  0.52961075  0.13366567]], shape=(3, 3), dtype=float32)


In [70]:
# transpose a matrix
x = tf.transpose(x, perm=[1, 0])
print(x)

tf.Tensor(
[[-0.60639316  0.3352423  -0.99884546]
 [-1.5211961   1.3196161   0.52961075]
 [-0.39179838  0.48279214  0.13366567]], shape=(3, 3), dtype=float32)
